package movistar.distribuidores.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-06T16:42:39.863+01:00
 * Generated source version: 2.7.3
 * 
 */

@WebService(targetNamespace = "http://ws.distribuidores.movistar", name = "BuscadorDistribuidoresPortType")
@XmlSeeAlso({movistar.distribuidores.bean.xsd.ObjectFactory.class, movistar.distribuidores.util.bean.xsd.ObjectFactory.class, ObjectFactory.class})
public interface BuscadorDistribuidoresPortType 
{


    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaCalle", output = "urn:busquedaCalleResponse")
    @RequestWrapper(localName = "busquedaCalle", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaCalle")
    @WebMethod(action = "urn:busquedaCalle")
    @ResponseWrapper(localName = "busquedaCalleResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaCalleResponse")
    public movistar.distribuidores.bean.xsd.CalleOut busquedaCalle(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.CalleIn entrada
    );


    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaDistribuidorCP", output = "urn:busquedaDistribuidorCPResponse")
    @RequestWrapper(localName = "busquedaDistribuidorCP", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorCP")
    @WebMethod(action = "urn:busquedaDistribuidorCP")
    @ResponseWrapper(localName = "busquedaDistribuidorCPResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorCPResponse")
    public movistar.distribuidores.bean.xsd.DistribuidorOut busquedaDistribuidorCP(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.DistribuidorPorCPIn entrada
    );

    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaCoordenadas", output = "urn:busquedaCoordenadasResponse")
    @RequestWrapper(localName = "busquedaCoordenadas", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaCoordenadas")
    @WebMethod(action = "urn:busquedaCoordenadas")
    @ResponseWrapper(localName = "busquedaCoordenadasResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaCoordenadasResponse")
    public movistar.distribuidores.bean.xsd.CoordenadasOut busquedaCoordenadas(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.CoordenadasIn entrada
    );


    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaProvincia", output = "urn:busquedaProvinciaResponse")
    @RequestWrapper(localName = "busquedaProvincia", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaProvincia")
    @WebMethod(action = "urn:busquedaProvincia")
    @ResponseWrapper(localName = "busquedaProvinciaResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaProvinciaResponse")
	 public movistar.distribuidores.bean.xsd.ProvinciaOut busquedaProvincia(
		        @WebParam(name = "listaServicio", targetNamespace = "http://ws.distribuidores.movistar")
		        movistar.distribuidores.util.bean.xsd.Servicio listaServicio
	);


    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaDistribuidor", output = "urn:busquedaDistribuidorResponse")
    @RequestWrapper(localName = "busquedaDistribuidor", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidor")
    @WebMethod(action = "urn:busquedaDistribuidor")
    @ResponseWrapper(localName = "busquedaDistribuidorResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorResponse")
    public movistar.distribuidores.bean.xsd.DistribuidorOut busquedaDistribuidor(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.DistribuidorPorCoordenadasIn entrada
    );


    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaPoblacion", output = "urn:busquedaPoblacionResponse")
    @RequestWrapper(localName = "busquedaPoblacion", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaPoblacion")
    @WebMethod(action = "urn:busquedaPoblacion")
    @ResponseWrapper(localName = "busquedaPoblacionResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaPoblacionResponse")
    public movistar.distribuidores.bean.xsd.PoblacionOut busquedaPoblacion(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.PoblacionIn entrada
    );

    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaDistribuidorDireccion", output = "urn:busquedaDistribuidorDireccionResponse")
    @RequestWrapper(localName = "busquedaDistribuidorDireccion", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorDireccion")
    @WebMethod(action = "urn:busquedaDistribuidorDireccion")
    @ResponseWrapper(localName = "busquedaDistribuidorDireccionResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorDireccionResponse")
    public movistar.distribuidores.bean.xsd.DistribuidorOut busquedaDistribuidorDireccion(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.DistribuidorPorDireccionIn entrada
    );

    @WebResult(name = "return", targetNamespace = "http://ws.distribuidores.movistar")
    @Action(input = "urn:busquedaDistribuidorCampo", output = "urn:busquedaDistribuidorCampoResponse")
    @RequestWrapper(localName = "busquedaDistribuidorCampo", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorCampo")
    @WebMethod(action = "urn:busquedaDistribuidorCampo")
    @ResponseWrapper(localName = "busquedaDistribuidorCampoResponse", targetNamespace = "http://ws.distribuidores.movistar", className = "movistar.distribuidores.ws.BusquedaDistribuidorCampoResponse")
    public movistar.distribuidores.bean.xsd.DistribuidorOut busquedaDistribuidorCampo(
        @WebParam(name = "entrada", targetNamespace = "http://ws.distribuidores.movistar")
        movistar.distribuidores.bean.xsd.DistribuidorPorCampoIn entrada
    );

}
